/**
 * lib/database/sqlite.ts
 *
 * Server-only: opens the pre-built portfolio.db and provides typed accessors.
 *
 * The database is a build artifact — generated by `scripts/index-portfolio.ts`
 * during `npm run build` and never written to at runtime. Opening it read-only
 * prevents any accidental mutation and is safe on serverless platforms that
 * mount the deployment as an immutable filesystem.
 *
 * Why not in-memory? The build step is the right time to do the heavy work:
 * FTS5 tokenisation and content-hashing. An in-memory build at request time
 * recomputes work that never changes between requests.
 *
 * Singleton per process: Next.js may reuse the same process across many
 * requests in production. Opening once and keeping the connection is both
 * correct (the file is read-only) and cheap (SQLite handles concurrent reads).
 */

import 'server-only';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import Database from 'better-sqlite3';

/* ---------------------------------------------------------------- paths */

const DB_PATH = resolve(process.cwd(), 'portfolio.db');

/* ------------------------------------------------------------ singleton */

let _db: Database.Database | null = null;

function openDb(): Database.Database {
  if (_db) return _db;
  if (!existsSync(DB_PATH)) {
    throw new Error(
      `portfolio.db not found at ${DB_PATH}. Run \`npm run index\` to generate it.`,
    );
  }
  _db = new Database(DB_PATH, { readonly: true, fileMustExist: true });
  return _db;
}

/* ---------------------------------------------------------------- types */

export interface DbEntity {
  id: string;
  type: string;
  name: string;
  slug: string | null;
  canonical_url: string | null;
  metadata_json: string;
  content_hash: string;
  created_at: string;
  updated_at: string;
}

export interface DbChunk {
  id: string;
  entity_id: string;
  chunk_type: string;
  title: string;
  content: string;
  content_hash: string;
  embedding_json: string | null;
  created_at: string;
}

export interface FtsResult {
  id: string;
  entity_id: string;
  entity_name: string;
  canonical_url: string | null;
  chunk_type: string;
  title: string;
  content: string;
  content_hash: string;
  embedding_json: string | null;
  created_at: string;
  /** BM25 rank from FTS5 (more negative = better match). */
  rank: number;
}

/* ------------------------------------------------------------- accessors */

/** Retrieve a single entity by its stable id (bare or compound). */
export function getEntity(id: string): DbEntity | null {
  const db = openDb();
  return (db.prepare('SELECT * FROM entities WHERE id = ?').get(id) as DbEntity | undefined) ?? null;
}

/** Retrieve all entities. */
export function getAllEntities(): DbEntity[] {
  const db = openDb();
  return db.prepare('SELECT * FROM entities').all() as DbEntity[];
}

/** Retrieve all chunks for a given entity id. */
export function getChunksByEntityId(entityId: string): DbChunk[] {
  const db = openDb();
  return db.prepare('SELECT * FROM chunks WHERE entity_id = ?').all(entityId) as DbChunk[];
}

/** Retrieve a chunk by its id. */
export function getChunk(id: string): DbChunk | null {
  const db = openDb();
  return (db.prepare('SELECT * FROM chunks WHERE id = ?').get(id) as DbChunk | undefined) ?? null;
}

/**
 * FTS5 full-text search over chunks with entity canonical URL resolution.
 *
 * Returns ranked results (BM25 by default in FTS5).
 */
export function ftsSearch(query: string, limit = 20): FtsResult[] {
  const db = openDb();
  const sanitised = sanitiseFtsQuery(query);
  if (!sanitised) return [];

  const rows = db
    .prepare(
      `SELECT c.id, c.entity_id, e.name as entity_name, e.canonical_url,
              c.chunk_type, c.title, c.content,
              c.content_hash, c.embedding_json, c.created_at, cf.rank
       FROM chunks_fts cf
       JOIN chunks c ON c.rowid = cf.rowid
       LEFT JOIN entities e ON e.id = c.entity_id
       WHERE chunks_fts MATCH ?
       ORDER BY cf.rank
       LIMIT ?`,
    )
    .all(sanitised, limit) as FtsResult[];

  return rows;
}

/**
 * Prevent FTS5 query errors from malformed input.
 *
 * FTS5 has its own query language (MATCH) and will throw on unbalanced quotes,
 * leading operators, etc. This sanitiser wraps each token in double quotes so
 * the input is always treated as a literal-phrase set rather than an FTS5
 * expression. Returns `null` when the query produces no usable tokens, so the
 * caller can skip the database round-trip entirely.
 */
function sanitiseFtsQuery(raw: string): string | null {
  const tokens = raw
    .trim()
    .replace(/["""]/g, '')
    .split(/\s+/)
    .filter((t) => t.length >= 2);
  if (tokens.length === 0) return null;
  return tokens.map((t) => `"${t}"`).join(' OR ');
}

/**
 * Resolve one or more entity IDs to their canonical URLs.
 *
 * Used by the reference validator: the LLM returns bare IDs, the application
 * resolves each against this table, and discards any that are not found.
 * Accepts both bare ids (`prod-verseye`) and compound keys (`products:prod-verseye`).
 *
 * Returns a Map so callers can do O(1) lookups per id.
 */
export function resolveEntityUrls(ids: string[]): Map<string, { name: string; type: string; canonical_url: string }> {
  if (ids.length === 0) return new Map();
  const db = openDb();

  const result = new Map<string, { name: string; type: string; canonical_url: string }>();
  for (const id of ids) {
    const row = db
      .prepare('SELECT id, name, type, canonical_url FROM entities WHERE id = ? AND canonical_url IS NOT NULL')
      .get(id) as { id: string; name: string; type: string; canonical_url: string } | undefined;
    if (row?.canonical_url) {
      result.set(id, { name: row.name, type: row.type, canonical_url: row.canonical_url });
    }
  }
  return result;
}

/** Confirm the database is reachable and has the expected tables. */
export function healthCheck(): { ok: boolean; entityCount: number; chunkCount: number } {
  try {
    const db = openDb();
    const entityCount = (db.prepare('SELECT COUNT(*) as n FROM entities').get() as { n: number }).n;
    const chunkCount = (db.prepare('SELECT COUNT(*) as n FROM chunks').get() as { n: number }).n;
    return { ok: true, entityCount, chunkCount };
  } catch {
    return { ok: false, entityCount: 0, chunkCount: 0 };
  }
}
