/**
 * lib/database/sqlite.ts
 *
 * Server-only: opens the pre-built portfolio.db and provides typed accessors.
 *
 * The database is a build artifact — generated by `scripts/index-portfolio.ts`
 * during `npm run build` and never written to at runtime. Opening it read-only
 * prevents any accidental mutation and is safe on serverless platforms that
 * mount the deployment as an immutable filesystem.
 *
 * Why not in-memory? The build step is the right time to do the heavy work:
 * FTS5 tokenisation and content-hashing. An in-memory build at request time
 * recomputes work that never changes between requests.
 *
 * Singleton per process: Next.js may reuse the same process across many
 * requests in production. Opening once and keeping the connection is both
 * correct (the file is read-only) and cheap (SQLite handles concurrent reads).
 */

import 'server-only';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import Database from 'better-sqlite3';

function resolveDbPath(): string {
  const candidates = [
    resolve(process.cwd(), 'portfolio.db'),
    resolve(process.cwd(), 'portfolio-os/portfolio.db'),
  ];
  for (const candidate of candidates) {
    if (existsSync(candidate)) return candidate;
  }
  return candidates[0]!;
}

const DB_PATH = resolveDbPath();

/* ------------------------------------------------------------ singleton */

let _db: Database.Database | null = null;

function openDb(): Database.Database {
  if (_db) return _db;
  if (!existsSync(DB_PATH)) {
    throw new Error(
      `portfolio.db not found at ${DB_PATH}. Run \`npm run index\` to generate it.`,
    );
  }
  _db = new Database(DB_PATH, { readonly: true, fileMustExist: true });
  return _db;
}

/* ---------------------------------------------------------------- types */

export interface DbEntity {
  id: string;
  type: string;
  name: string;
  slug: string | null;
  canonical_url: string | null;
  metadata_json: string;
  content_hash: string;
  created_at: string;
  updated_at: string;
}

export interface DbChunk {
  id: string;
  entity_id: string;
  chunk_type: string;
  title: string;
  content: string;
  content_hash: string;
  embedding_json: string | null;
  created_at: string;
}

export interface FtsResult {
  id: string;
  entity_id: string;
  entity_name: string;
  canonical_url: string | null;
  chunk_type: string;
  title: string;
  content: string;
  content_hash: string;
  embedding_json: string | null;
  created_at: string;
  /** BM25 rank from FTS5 (more negative = better match). */
  rank: number;
}

import { getPortfolioRepository } from '../repositories/server';

/* ------------------------------------------------------------- accessors */

/** Retrieve a single entity by its stable id (bare or compound). */
export function getEntity(id: string): DbEntity | null {
  const entity = getPortfolioRepository().getEntity(id);
  if (!entity) return null;
  return {
    id: entity.id,
    type: entity.type,
    name: entity.name,
    slug: entity.slug,
    canonical_url: entity.canonicalUrl,
    metadata_json: entity.metadataJson,
    content_hash: entity.contentHash,
    created_at: entity.createdAt ?? '',
    updated_at: entity.updatedAt ?? '',
  };
}

/** Retrieve all entities. */
export function getAllEntities(): DbEntity[] {
  return getPortfolioRepository().getAllEntities().map((entity) => ({
    id: entity.id,
    type: entity.type,
    name: entity.name,
    slug: entity.slug,
    canonical_url: entity.canonicalUrl,
    metadata_json: entity.metadataJson,
    content_hash: entity.contentHash,
    created_at: entity.createdAt ?? '',
    updated_at: entity.updatedAt ?? '',
  }));
}

/** Retrieve all chunks for a given entity id. */
export function getChunksByEntityId(entityId: string): DbChunk[] {
  return getPortfolioRepository().getChunksByEntityId(entityId).map((chunk) => ({
    id: chunk.id,
    entity_id: chunk.entityId,
    chunk_type: chunk.chunkType,
    title: chunk.title,
    content: chunk.content,
    content_hash: chunk.contentHash,
    embedding_json: chunk.embeddingJson ?? null,
    created_at: chunk.createdAt ?? '',
  }));
}

/** Retrieve a chunk by its id. */
export function getChunk(id: string): DbChunk | null {
  const chunk = getPortfolioRepository().getChunk(id);
  if (!chunk) return null;
  return {
    id: chunk.id,
    entity_id: chunk.entityId,
    chunk_type: chunk.chunkType,
    title: chunk.title,
    content: chunk.content,
    content_hash: chunk.contentHash,
    embedding_json: chunk.embeddingJson ?? null,
    created_at: chunk.createdAt ?? '',
  };
}

/**
 * FTS5 full-text search over chunks with entity canonical URL resolution.
 *
 * Returns ranked results (BM25 by default in FTS5).
 */
export function ftsSearch(query: string, limit = 20): FtsResult[] {
  const hits = getPortfolioRepository().search(query, limit);
  return (hits as any[]).map((hit) => ({
    id: hit.id,
    entity_id: hit.entityId,
    entity_name: hit.entityName,
    canonical_url: hit.canonicalUrl,
    chunk_type: hit.chunkType,
    title: hit.title,
    content: hit.content,
    content_hash: hit.contentHash,
    embedding_json: hit.embeddingJson ?? null,
    created_at: hit.createdAt ?? '',
    rank: hit.rank,
  }));
}

/**
 * Prevent FTS5 query errors from malformed input.
 */
function sanitiseFtsQuery(raw: string): string | null {
  const tokens = raw
    .trim()
    .replace(/["""]/g, '')
    .split(/\s+/)
    .filter((t) => t.length >= 2);
  if (tokens.length === 0) return null;
  return tokens.map((t) => `"${t}"`).join(' OR ');
}

/**
 * Resolve one or more entity IDs to their canonical URLs.
 *
 * Used by the reference validator: the LLM returns bare IDs, the application
 * resolves each against this table, and discards any that are not found.
 * Accepts both bare ids (`prod-verseye`) and compound keys (`products:prod-verseye`).
 *
 * Returns a Map so callers can do O(1) lookups per id.
 */
export function resolveEntityUrls(ids: string[]): Map<string, { name: string; type: string; canonical_url: string }> {
  return getPortfolioRepository().resolveEntityUrls(ids) as Map<string, { name: string; type: string; canonical_url: string }>;
}

/** Confirm the database is reachable and has the expected tables. */
export function healthCheck(): { ok: boolean; entityCount: number; chunkCount: number } {
  const health = getPortfolioRepository().healthCheck();
  return {
    ok: health.ok,
    entityCount: health.entityCount,
    chunkCount: health.chunkCount,
  };
}

